import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const frizQuadrata = localFont({
  src: "./fonts/FrizQuadrataRegular.woff",
  variable: "--font-friz-quadrata",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${frizQuadrata.variable} antialiased`}>{children}</body>
      <footer className="bg-[#0A1428] bg-opacity-90 border-t border-[#785A28] p-4 mt-12">
        <div className="container mx-auto text-center text-sm">
          <p>&copy; 2024 LoLO (League of Legends Optimizer). All rights reserved.</p>
          <div className="mt-2">
            <Link href="/terms" className="text-[#3C95D4] hover:underline mr-4">
              Terms of Service
            </Link>
            <Link href="/privacy" className="text-[#3C95D4] hover:underline">
              Privacy Policy
            </Link>
          </div>
        </div>
      </footer>
    </html>
  );
}
